TestMain, LedgerStorageCheckpointTest: fix powermock ignore
testBuildBookieServer(org.apache.bookkeeper.server.TestMain)  Time elapsed: 0.996 sec  <<< ERROR!
java.util.ServiceConfigurationError: org.apache.logging.log4j.util.PropertySource: Provider org.apache.logging.log4j.util.EnvironmentPropertySource not a subtype
    at org.apache.bookkeeper.server.TestMain.testBuildBookieServer(TestMain.java:76)

Introduced: 89de4115e297f70e6fc61507359a24e4040602b5

Signed-off-by: Samuel Just <sjust@salesforce.com>